### ISSUE TITLE
eth_getBlockReceipts pre-bedrock?

### ISSUE THREAD

**Issue by quickchase** [sunnyside-io/op-erigon#71]
`eth_getBlockReceipts` seems to work just fine for blocks after the fork (> `105235062`) but I get `method handler crashed` for pre:

```
curl -s -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockReceipts","params":["0x645c270"]}' localhost:8545

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```

Expected, or bug?

**Comment by pcw109550** [comment]
It seems to be a bug. Will inspect.
Confirmed using our public RPC: https://op-erigon.mainnet.testinprod.io

**Comment by pcw109550** [comment]
### Root Cause Analysis

Chainspec misconfiguration(introduced at https://github.com/testinprod-io/op-erigon/pull/64) caused receipt marshaling to panic. More specifically, EIP-1559 is activated using London fork block number. London fork block number must be configured as start of bedrock, `105235063`, but it was misconfigured as `3950000`. This misconfig caused all transactions receipts in block `3950000` ~ `105235063 - 1` to be not marshaled and cause null pointer exception. Prebedrock blocks do not contain `BaseFee` field, causing error. Relevant code:

https://github.com/testinprod-io/op-erigon/blob/8f7c283e144c5fabfa06b904ffb643390e031856/cmd/rpcdaemon/commands/eth_receipts.go#L751-L757

### Mitigation

1. Fix chainspec of optimism mainnet stored at [params/chainspecs/optimism-mainnet.json](https://github.com/testinprod-io/op-erigon/blob/op-erigon/params/chainspecs/optimism-mainnet.json)
2. Fix chainspec stored at archive database: https://op-erigon-backup.mainnet.testinprod.io
3. (Optional) Provide command line utility to fix incorrect database. This makes users not to download the db again and resync. 
4. (Optional) Apply defensive programming to above code segments; for example checking `header.BaseFee` is not nil etc.

The fix will likely be implemented ASAP.

**Comment by pcw109550** [comment]
@quickchase we have released https://github.com/testinprod-io/op-erigon/releases/tag/v2.43.0-0.1.5 which fixes this bug.

**Comment by quickchase** [comment]
Hmmm I just updated the node to that release and the above cURL still crashes, do I need to do anything?

**Comment by quickchase** [comment]
Confirmed that the above cURL works on new version
